parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: edusoho
    database_user: root
    database_password: ''
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: lnlpthszli8g44wc8ko4owgskcwoccc
    webpack_base_url: http://127.0.0.1
    user_partner: none